import { ref } from 'vue'
import { escapeHtml } from '@/utils/html.ts'
import { useAppMode } from '@/composables/useAppMode.ts'
import { usePortForward } from '@/composables/usePortForward.ts'
import { useToast } from '@/composables/useToast.ts'
import { gt } from '@/composables/useLocale'

/**
 * Localhost URL annotation composable.
 *
 * Detects localhost URLs (http://localhost:PORT, https://localhost:PORT,
 * http://127.0.0.1:PORT, https://127.0.0.1:PORT) in rendered chat HTML
 * and appends a clickable EthernetPort icon button after them.
 *
 * The <a> tag itself is preserved intact; a small button is appended after it,
 * exactly like the file-path open button pattern in useFilePathAnnotation.ts.
 * Clicking either the <a> link or the icon button triggers the same
 * port-forward-and-open-WebView flow.
 */

/** Regex to match bare localhost URLs in text (not inside <a> tags) */
const LOCALHOST_URL_RE = /https?:\/\/(?:localhost|127\.0\.0\.1):(\d+)(\/[^\s<>"')\]]*)?/gi

/**
 * Check if an href points to a localhost address.
 */
export function isLocalhostUrl(href: string): boolean {
    return /^https?:\/\/(?:localhost|127\.0\.0\.1):\d+/i.test(href)
}

/**
 * Parse a localhost URL into its components.
 * Returns null if not a localhost URL.
 */
export function parseLocalhostUrl(url: string): { port: number; protocol: string; fullUrl: string } | null {
    const match = url.match(/^((https?):\/\/(?:localhost|127\.0\.0\.1):(\d+))/i)
    if (!match) return null
    return {
        port: parseInt(match[3]),
        protocol: match[2].toLowerCase(),
        fullUrl: match[1],
    }
}

/**
 * SVG icon markup for the localhost open button (EthernetPort icon from lucide).
 * Same pattern as FILE_OPEN_ICON_SVG in useFilePathAnnotation.ts.
 */
export const LOCALHOST_OPEN_ICON_SVG = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="12" height="12"><path d="m15 20 3-3h2a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h2l3 3z"/><path d="M6 8v1"/><path d="M10 8v1"/><path d="M14 8v1"/><path d="M18 8v1"/></svg>'

/**
 * Generate HTML for the localhost open button (EthernetPort icon).
 * Same pattern as fileOpenButtonHtml() in useFilePathAnnotation.ts.
 */
export function localhostOpenButtonHtml(port: number, protocol: string, url: string): string {
    return `<button class="chat-url-open-btn" data-url="${escapeHtml(url)}" data-port="${port}" data-protocol="${escapeHtml(protocol)}" title="Open in WebView">${LOCALHOST_OPEN_ICON_SVG}</button>`
}

/**
 * Detect localhost URLs in rendered HTML and append clickable icon buttons.
 *
 * Uses DOMParser + TreeWalker for robust HTML traversal (same architecture as
 * useFilePathAnnotation, useWorktreeAnnotation, useCommitHashAnnotation).
 * This avoids the class of bugs where string-based regex + placeholder protection
 * can match inside HTML attributes generated by earlier annotation passes.
 *
 * Processing order:
 *   1. <a href> tags with localhost hrefs → append icon button after
 *   2. <code> tags whose entire content is a localhost URL → wrap in <a>, append button
 *   3. Text nodes (outside <a>) → regex match bare localhost URLs → insert <a> + button
 *
 * Unlike file paths, localhost URLs inside <code> backticks ARE annotated (they are
 * typically meant to be clickable — e.g. `http://localhost:20003`).
 *
 * Returns the annotated HTML.
 */
export function annotateLocalhostUrls(html: string): string {
    if (!html) return html

    // Only annotate in App mode — web mode can access localhost directly,
    // no port forwarding or built-in WebView needed
    const { isAppMode } = useAppMode()
    if (!isAppMode.value) return html

    // Skip annotation when SSH is disabled (no port forwarding available)
    const { sshInfo } = usePortForward()
    if (sshInfo.value?.enabled === false) return html

    const doc = new DOMParser().parseFromString(html, 'text/html')

    // ── Step 1: <a href> tags with localhost hrefs → append icon button ──
    for (const a of doc.querySelectorAll('a[href]')) {
        const href = a.getAttribute('href') || ''
        const parsed = parseLocalhostUrl(href)
        if (!parsed) continue
        if (parsed.port <= 0 || parsed.port > 65535) continue
        a.insertAdjacentHTML('afterend', localhostOpenButtonHtml(parsed.port, parsed.protocol, parsed.fullUrl))
    }

    // ── Step 2: <code> tags whose entire content is a localhost URL ──
    // Unlike file paths, localhost URLs in backticks are meant to be clickable.
    // Wrap the <code> in <a> and append the icon button.
    for (const code of doc.querySelectorAll('code')) {
        const stripped = (code.textContent || '').trim()
        const parsed = parseLocalhostUrl(stripped)
        if (!parsed) continue
        if (parsed.port <= 0 || parsed.port > 65535) continue
        // Wrap the <code> in an <a> tag
        const wrapper = doc.createElement('a')
        wrapper.setAttribute('href', parsed.fullUrl)
        wrapper.setAttribute('target', '_blank')
        wrapper.setAttribute('rel', 'noopener')
        code.parentNode!.replaceChild(wrapper, code)
        wrapper.appendChild(code)
        // Append icon button after the <a>
        wrapper.insertAdjacentHTML('afterend', localhostOpenButtonHtml(parsed.port, parsed.protocol, parsed.fullUrl))
    }

    // ── Step 3: Text nodes (outside <a>) → regex match bare localhost URLs ──
    const textNodes: Text[] = []
    const walker = doc.createTreeWalker(doc.body, NodeFilter.SHOW_TEXT, {
        acceptNode(node: Text) {
            const parent = node.parentElement
            if (!parent) return NodeFilter.FILTER_REJECT
            // Skip text inside <a> tags (handled in step 1, and step 2's wrappers)
            if (parent.tagName === 'A' || parent.closest('a')) return NodeFilter.FILTER_REJECT
            return NodeFilter.FILTER_ACCEPT
        }
    })
    while (walker.nextNode()) textNodes.push(walker.currentNode as Text)

    // Process text nodes in reverse order so that DOM insertions
    // don't invalidate later node positions.
    for (let i = textNodes.length - 1; i >= 0; i--) {
        const textNode = textNodes[i]
        const text = textNode.textContent || ''
        LOCALHOST_URL_RE.lastIndex = 0
        if (!LOCALHOST_URL_RE.test(text)) continue

        // Re-run regex to collect matches (test() consumed lastIndex)
        LOCALHOST_URL_RE.lastIndex = 0
        const parts: Array<{ text: string; url: string | null; port: number; protocol: string }> = []
        let lastIndex = 0
        let match: RegExpExecArray | null
        while ((match = LOCALHOST_URL_RE.exec(text)) !== null) {
            const url = match[0]
            const port = parseInt(match[1])
            if (port <= 0 || port > 65535) {
                // Invalid port — treat as plain text
                if (match.index > lastIndex) {
                    parts.push({ text: text.slice(lastIndex, match.index), url: null, port: 0, protocol: '' })
                }
                parts.push({ text: url, url: null, port: 0, protocol: '' })
                lastIndex = match.index + url.length
                continue
            }
            const protocol = url.startsWith('https') ? 'https' : 'http'
            // Push text before this match
            if (match.index > lastIndex) {
                parts.push({ text: text.slice(lastIndex, match.index), url: null, port: 0, protocol: '' })
            }
            parts.push({ text: url, url, port, protocol })
            lastIndex = match.index + url.length
        }
        // Push remaining text after last match
        if (lastIndex < text.length) {
            parts.push({ text: text.slice(lastIndex), url: null, port: 0, protocol: '' })
        }

        // Build replacement nodes
        const parent = textNode.parentNode!
        const frag = doc.createDocumentFragment()
        let hasAnnotation = false
        for (const part of parts) {
            if (part.url) {
                hasAnnotation = true
                const a = doc.createElement('a')
                a.setAttribute('href', part.url)
                a.setAttribute('target', '_blank')
                a.setAttribute('rel', 'noopener')
                a.textContent = part.text
                frag.appendChild(a)
                // Open button (as HTML snippet since it contains SVG)
                const btnContainer = doc.createElement('span')
                btnContainer.innerHTML = localhostOpenButtonHtml(part.port, part.protocol, part.url)
                while (btnContainer.firstChild) frag.appendChild(btnContainer.firstChild)
            } else {
                frag.appendChild(doc.createTextNode(part.text))
            }
        }

        if (hasAnnotation) {
            parent.replaceChild(frag, textNode)
        }
    }

    return doc.body.innerHTML
}

/**
 * Composable for handling localhost URL click events in rendered chat HTML.
 *
 * Provides two reusable functions that encapsulate the shared click-handling logic
 * used by ChatMessageList, ToolDetailOverlay, and TaskExecDetail:
 *
 * - handleLocalhostUrlClick(event): inspects a click event for .chat-url-open-btn
 *   or <a href="localhost:..."> targets, intercepts the default navigation, and
 *   opens via SSH tunnel + WebView instead. Returns true if the event was handled.
 *
 * - openLocalhostUrl(element, port, protocol): low-level async function that
 *   ensures a port is registered for forwarding and opens it in the WebView.
 *
 * Usage in a component:
 *   const { handleLocalhostUrlClick } = useLocalhostUrlClickHandler()
 *   // In your @click handler:
 *   if (handleLocalhostUrlClick(event)) return
 */
export function useLocalhostUrlClickHandler() {
    const { isAppMode } = useAppMode()
    const { ensurePortRegistered, openPort, sshInfo } = usePortForward()
    const toast = useToast()

    // Module-level guard to prevent double-clicks
    const urlOpening = ref(false)

    /**
     * Open a localhost URL: ensure port forwarding is set up, then open in WebView.
     * Returns false if SSH is disabled (caller may choose to fall through to default navigation).
     */
    async function openLocalhostUrl(element: Element, port: number, protocol: string): Promise<boolean> {
        if (urlOpening.value) return true
        if (sshInfo.value?.enabled === false) {
            toast.show(gt('chat.localhost.sshDisabled'), { type: 'info' })
            return false
        }
        urlOpening.value = true
        element.classList.add('loading')

        try {
            const localPort = await ensurePortRegistered(port, protocol)
            await openPort(localPort, protocol)
        } catch (err) {
            toast.show(gt('chat.localhost.openFailed'), { type: 'error' })
        } finally {
            urlOpening.value = false
            element.classList.remove('loading')
        }
        return true
    }

    /**
     * Handle a click event that may target a localhost URL element.
     *
     * Checks for two targets (App mode only):
     * 1. .chat-url-open-btn — the icon button appended after localhost URLs
     * 2. <a href="localhost:..."> — direct link clicks on localhost URLs
     *
     * If either is found and SSH tunnel is available, prevents default navigation,
     * ensures the port is registered for forwarding, and opens via SSH tunnel + WebView.
     * If SSH is disabled, shows a warning toast and does NOT prevent default navigation
     * (allows the <a> tag to fall through to the browser).
     *
     * Returns true if the click was handled (caller should stop processing).
     */
    function handleLocalhostUrlClick(event: MouseEvent): boolean {
        if (!isAppMode.value) return false

        const urlBtn = (event.target as Element).closest('.chat-url-open-btn')
        if (urlBtn) {
            // Icon button: always preventDefault (no useful default behavior),
            // but show toast if SSH is disabled
            event.preventDefault()
            event.stopPropagation()
            const port = parseInt(urlBtn.getAttribute('data-port') || '0')
            const protocol = urlBtn.getAttribute('data-protocol') || 'http'
            if (port > 0) {
                openLocalhostUrl(urlBtn, port, protocol)
            }
            return true
        }

        const anchor = (event.target as Element).closest('a[href]')
        if (anchor) {
            const href = anchor.getAttribute('href') || ''
            if (isLocalhostUrl(href)) {
                const parsed = parseLocalhostUrl(href)
                if (parsed) {
                    // Fire-and-forget: the async result tells us whether to
                    // prevent default navigation or let the browser handle it.
                    // We must prevent navigation eagerly to avoid the race,
                    // but if openLocalhostUrl returns false (SSH disabled),
                    // we re-trigger the <a> navigation manually.
                    event.preventDefault()
                    event.stopPropagation()
                    openLocalhostUrl(anchor, parsed.port, parsed.protocol).then(handled => {
                        if (!handled) {
                            // SSH disabled — fall through to default browser navigation
                            window.open(href, '_blank')
                        }
                    })
                }
                return true
            }
        }

        return false
    }

    return { handleLocalhostUrlClick, openLocalhostUrl }
}

/**
 * Composable for localhost URL annotation in rendered HTML (v-html content).
 */
export function useLocalhostAnnotation() {
    return {
        annotateLocalhostUrls,
        isLocalhostUrl,
        parseLocalhostUrl,
        localhostOpenButtonHtml,
    }
}
